In [6]:
import numpy as np
import pandas as pd
from pathlib import Path

import os
import random
import shutil
from sklearn.model_selection import train_test_split

In [14]:
PATH_ = Path('keypoints_data/mediapipe/train/Swing')

for npy_file in PATH_.glob('*.npy'):
    array = np.load(npy_file)
    #print('shape:', array.shape)
    #print(np.min(array), np.max(array))

zero_chunks = 0
total_chunks = 0

for npy_file in PATH_.glob('*.npy'):

    array = np.load(npy_file)

    total_chunks += 1

    if np.all(array == 0):
        zero_chunks += 1

print(f'Total chunks: {total_chunks}')
print(f'Zero chunks: {zero_chunks}')
print(f'Percent: {100 * zero_chunks / total_chunks:.2f}%')

Total chunks: 350
Zero chunks: 25
Percent: 7.14%

In [21]:
PATH_ = Path('keypoints_data/mediapipe/test/TableTennisShot')

for npy_file in PATH_.glob('*.npy'):
    array = np.load(npy_file)
    #print('shape:', array.shape)
    #print(np.min(array), np.max(array))


zero_chunks = 0
total_chunks = 0

for npy_file in PATH_.glob('*.npy'):

    array = np.load(npy_file)

    total_chunks += 1

    if np.all(array == 0):
        zero_chunks += 1

print(f'Total chunks: {total_chunks}')
print(f'Zero chunks: {zero_chunks}')
print(f'Percent: {100 * zero_chunks / total_chunks:.2f}%')

Total chunks: 67
Zero chunks: 3
Percent: 4.48%

In [2]:
SOURCE_DIR = "data/Kinetics/train"
OUTPUT_DIR = "data/Kinetics_split"

TRAIN_SIZE = 0.7
VAL_SIZE = 0.15
TEST_SIZE = 0.15

VIDEO_EXTENSIONS = [".avi", ".mp4", ".mov", ".mkv"]
RANDOM_STATE = 42

for split in ["train", "val", "test"]:
    os.makedirs(os.path.join(OUTPUT_DIR, split), exist_ok=True)

def is_video_file(filename):
    return Path(filename).suffix.lower() in VIDEO_EXTENSIONS


def collect_videos(class_dir):
    videos = []

    for file in os.listdir(class_dir):
        if is_video_file(file):
            videos.append(file)

    return videos


def copy_and_collect_metadata(files, class_name, split_name):
    metadata = []

    split_class_dir = os.path.join(OUTPUT_DIR, split_name, class_name)
    os.makedirs(split_class_dir, exist_ok=True)

    source_class_dir = os.path.join(SOURCE_DIR, class_name)

    for file_name in files:
        src_path = os.path.join(source_class_dir, file_name)
        dst_path = os.path.join(split_class_dir, file_name)

        # Копирование файла
        shutil.copy2(src_path, dst_path)

        # clip_name без расширения
        clip_name = Path(file_name).stem

        # относительный путь
        relative_path = f"/{split_name}/{class_name}/{file_name}"

        metadata.append({
            "clip_name": clip_name,
            "clip_path": relative_path,
            "label": class_name
        })

    return metadata



all_train_metadata = []
all_val_metadata = []
all_test_metadata = []

classes = sorted(os.listdir(SOURCE_DIR))

for class_name in classes:

    class_dir = os.path.join(SOURCE_DIR, class_name)

    if not os.path.isdir(class_dir):
        continue

    videos = collect_videos(class_dir)

    if len(videos) == 0:
        continue

    train_files, temp_files = train_test_split(
        videos,
        test_size=(1 - TRAIN_SIZE),
        random_state=RANDOM_STATE
    )

    val_ratio_adjusted = VAL_SIZE / (VAL_SIZE + TEST_SIZE)

    val_files, test_files = train_test_split(
        temp_files,
        test_size=(1 - val_ratio_adjusted),
        random_state=RANDOM_STATE
    )

    
    all_train_metadata.extend(
        copy_and_collect_metadata(train_files, class_name, "train")
    )

    all_val_metadata.extend(
        copy_and_collect_metadata(val_files, class_name, "val")
    )

    all_test_metadata.extend(
        copy_and_collect_metadata(test_files, class_name, "test")
    )

    print(
        f"{class_name}: "
        f"train={len(train_files)}, "
        f"val={len(val_files)}, "
        f"test={len(test_files)}"
    )


train_df = pd.DataFrame(all_train_metadata)
val_df = pd.DataFrame(all_val_metadata)
test_df = pd.DataFrame(all_test_metadata)

train_df.to_csv(
    os.path.join(OUTPUT_DIR, "train.csv"),
    index=False
)

val_df.to_csv(
    os.path.join(OUTPUT_DIR, "val.csv"),
    index=False
)

test_df.to_csv(
    os.path.join(OUTPUT_DIR, "test.csv"),
    index=False
)

print("\nDONE!")
print(f"Dataset saved to: {OUTPUT_DIR}")

abseiling: train=32, val=7, test=7
air drumming: train=31, val=7, test=7
answering questions: train=9, val=2, test=2
applauding: train=6, val=2, test=2
applying cream: train=9, val=2, test=2
archery: train=31, val=7, test=7
arm wrestling: train=30, val=6, test=7
arranging flowers: train=12, val=3, test=3
assembling computer: train=11, val=2, test=3
auctioning: train=10, val=2, test=3
baby waking up: train=13, val=3, test=4
baking cookies: train=22, val=5, test=5
balloon blowing: train=18, val=4, test=5
bandaging: train=12, val=3, test=3
barbequing: train=28, val=6, test=7
bartending: train=13, val=3, test=3
beatboxing: train=23, val=5, test=6
bee keeping: train=8, val=2, test=2
belly dancing: train=25, val=6, test=6
bench pressing: train=30, val=7, test=7
bending back: train=14, val=3, test=4
bending metal: train=7, val=2, test=2
biking through snow: train=29, val=6, test=7
blasting sand: train=18, val=4, test=5
blowing glass: train=30, val=6, test=7
blowing leaves: train=7, val=2, test=2
blowing nose: train=13, val=3, test=3
blowing out candles: train=32, val=7, test=8
bobsledding: train=14, val=3, test=4
bookbinding: train=24, val=5, test=6
bouncing on trampoline: train=16, val=3, test=4
bowling: train=29, val=6, test=7
braiding hair: train=16, val=3, test=4
breading or breadcrumbing: train=9, val=2, test=2
breakdancing: train=25, val=5, test=6
brush painting: train=11, val=3, test=3
brushing hair: train=23, val=5, test=5
brushing teeth: train=32, val=7, test=7
building cabinet: train=8, val=2, test=2
building shed: train=9, val=2, test=2
bungee jumping: train=29, val=6, test=7
busking: train=23, val=5, test=5
canoeing or kayaking: train=32, val=7, test=8
capoeira: train=30, val=7, test=7
carrying baby: train=13, val=3, test=3
cartwheeling: train=13, val=3, test=4
carving pumpkin: train=15, val=3, test=4
catching fish: train=15, val=3, test=4
catching or throwing baseball: train=18, val=4, test=5
catching or throwing frisbee: train=27, val=6, test=7
catching or throwing softball: train=21, val=5, test=5
celebrating: train=17, val=4, test=4
changing oil: train=16, val=4, test=4
changing wheel: train=9, val=2, test=3
checking tires: train=11, val=3, test=3
cheerleading: train=32, val=7, test=7
chopping wood: train=24, val=5, test=6
clapping: train=10, val=2, test=3
clay pottery making: train=6, val=2, test=2
clean and jerk: train=24, val=5, test=6
cleaning floor: train=22, val=5, test=5
cleaning gutters: train=13, val=3, test=4
cleaning pool: train=9, val=2, test=2
cleaning shoes: train=15, val=3, test=4
cleaning toilet: train=11, val=3, test=3
cleaning windows: train=16, val=4, test=4
climbing a rope: train=8, val=2, test=2
climbing ladder: train=16, val=4, test=4
climbing tree: train=29, val=6, test=7
contact juggling: train=31, val=7, test=7
cooking chicken: train=25, val=6, test=6
cooking egg: train=13, val=3, test=4
cooking on campfire: train=7, val=2, test=2
cooking sausages: train=9, val=2, test=2
counting money: train=14, val=3, test=4
country line dancing: train=28, val=6, test=7
cracking neck: train=7, val=2, test=2
crawling baby: train=32, val=7, test=7
crossing river: train=25, val=6, test=6
crying: train=25, val=6, test=6
curling hair: train=20, val=4, test=5
cutting nails: train=11, val=3, test=3
cutting pineapple: train=16, val=4, test=4
cutting watermelon: train=17, val=4, test=4
dancing ballet: train=32, val=7, test=7
dancing charleston: train=17, val=4, test=4
dancing gangnam style: train=20, val=5, test=5
dancing macarena: train=25, val=5, test=6
deadlifting: train=20, val=4, test=5
decorating the christmas tree: train=13, val=3, test=3
digging: train=7, val=2, test=2
dining: train=16, val=4, test=4
disc golfing: train=13, val=3, test=3
diving cliff: train=29, val=6, test=7
dodgeball: train=14, val=3, test=4
doing aerobics: train=9, val=2, test=2
doing laundry: train=9, val=2, test=2
doing nails: train=23, val=5, test=5
drawing: train=7, val=2, test=2
dribbling basketball: train=23, val=5, test=6
drinking: train=13, val=3, test=4
drinking beer: train=12, val=3, test=3
drinking shots: train=7, val=2, test=2
driving car: train=26, val=6, test=6
driving tractor: train=23, val=5, test=6
drop kicking: train=18, val=4, test=4
drumming fingers: train=7, val=2, test=2
dunking basketball: train=29, val=6, test=7
dying hair: train=26, val=6, test=6
eating burger: train=20, val=5, test=5
eating cake: train=10, val=2, test=3
eating carrots: train=11, val=2, test=3
eating chips: train=17, val=4, test=4
eating doughnuts: train=11, val=2, test=3
eating hotdog: train=12, val=3, test=3
eating ice cream: train=24, val=5, test=6
eating spaghetti: train=32, val=7, test=7
eating watermelon: train=11, val=3, test=3
egg hunting: train=11, val=2, test=3
exercising arm: train=7, val=2, test=2
exercising with an exercise ball: train=8, val=2, test=2
extinguishing fire: train=13, val=3, test=3
faceplanting: train=8, val=2, test=2
feeding birds: train=31, val=7, test=7
feeding fish: train=25, val=6, test=6
feeding goats: train=27, val=6, test=7
filling eyebrows: train=25, val=5, test=6
finger snapping: train=22, val=5, test=5
fixing hair: train=14, val=3, test=4
flipping pancake: train=17, val=4, test=4
flying kite: train=29, val=6, test=7
folding clothes: train=15, val=3, test=4
folding napkins: train=21, val=5, test=5
folding paper: train=20, val=5, test=5
front raises: train=25, val=5, test=6
frying vegetables: train=12, val=3, test=3
garbage collecting: train=9, val=2, test=2
gargling: train=7, val=2, test=2
getting a haircut: train=16, val=3, test=4
getting a tattoo: train=18, val=4, test=4
giving or receiving award: train=25, val=5, test=6
golf chipping: train=16, val=4, test=4
golf driving: train=22, val=5, test=5
golf putting: train=30, val=6, test=7
grinding meat: train=7, val=2, test=2
grooming dog: train=13, val=3, test=4
grooming horse: train=14, val=3, test=4
gymnastics tumbling: train=30, val=7, test=7
hammer throw: train=32, val=7, test=7
headbanging: train=30, val=6, test=7
headbutting: train=15, val=3, test=4
high jump: train=25, val=6, test=6
high kick: train=20, val=5, test=5
hitting baseball: train=29, val=6, test=7
hockey stop: train=9, val=2, test=3
holding snake: train=7, val=2, test=2
hopscotch: train=18, val=4, test=4
hoverboarding: train=9, val=2, test=2
hugging: train=11, val=2, test=3
hula hooping: train=31, val=7, test=7
hurdling: train=15, val=3, test=4
hurling (sport): train=22, val=5, test=5
ice climbing: train=22, val=5, test=5
ice fishing: train=13, val=3, test=3
ice skating: train=30, val=7, test=7
ironing: train=11, val=2, test=3
javelin throw: train=24, val=5, test=6
jetskiing: train=32, val=7, test=7
jogging: train=7, val=2, test=2
juggling balls: train=24, val=5, test=6
juggling fire: train=16, val=4, test=4
juggling soccer ball: train=9, val=2, test=3
jumping into pool: train=30, val=7, test=7
jumpstyle dancing: train=16, val=3, test=4
kicking field goal: train=21, val=5, test=5
kicking soccer ball: train=11, val=3, test=3
kissing: train=11, val=2, test=3
kitesurfing: train=20, val=5, test=5
knitting: train=16, val=4, test=4
krumping: train=16, val=3, test=4
laughing: train=22, val=5, test=5
laying bricks: train=8, val=2, test=2
long jump: train=22, val=5, test=5
lunge: train=18, val=4, test=5
making a cake: train=8, val=2, test=2
making a sandwich: train=8, val=2, test=2
making bed: train=16, val=3, test=4
making jewelry: train=15, val=3, test=4
making pizza: train=30, val=7, test=7
making snowman: train=18, val=4, test=5
making sushi: train=8, val=2, test=2
making tea: train=7, val=2, test=2
marching: train=32, val=7, test=7
massaging back: train=21, val=5, test=5
massaging feet: train=7, val=2, test=2
massaging legs: train=8, val=2, test=2
massaging person's head: train=13, val=3, test=4
milking cow: train=25, val=6, test=6
mopping floor: train=13, val=3, test=4
motorcycling: train=28, val=6, test=7
moving furniture: train=8, val=2, test=2
mowing lawn: train=31, val=7, test=7
news anchoring: train=7, val=2, test=2
opening bottle: train=17, val=4, test=4
opening present: train=22, val=5, test=5
paragliding: train=20, val=5, test=5
parasailing: train=19, val=4, test=5
parkour: train=10, val=2, test=3
passing American football (in game): train=24, val=5, test=6
passing American football (not in game): train=27, val=6, test=6
peeling apples: train=13, val=3, test=3
peeling potatoes: train=8, val=2, test=2
petting animal (not cat): train=19, val=4, test=5
petting cat: train=17, val=4, test=4
picking fruit: train=20, val=4, test=5
planting trees: train=12, val=3, test=3
plastering: train=8, val=2, test=2
playing accordion: train=23, val=5, test=6
playing badminton: train=24, val=5, test=6
playing bagpipes: train=21, val=5, test=5
playing basketball: train=30, val=6, test=7
playing bass guitar: train=30, val=6, test=7
playing cards: train=18, val=4, test=4
playing cello: train=29, val=6, test=7
playing chess: train=20, val=4, test=5
playing clarinet: train=27, val=6, test=7
playing controller: train=11, val=3, test=3
playing cricket: train=20, val=5, test=5
playing cymbals: train=16, val=3, test=4
playing didgeridoo: train=20, val=5, test=5
playing drums: train=23, val=5, test=6
playing flute: train=9, val=2, test=3
playing guitar: train=30, val=6, test=7
playing harmonica: train=27, val=6, test=6
playing harp: train=32, val=7, test=7
playing ice hockey: train=23, val=5, test=5
playing keyboard: train=17, val=4, test=4
playing kickball: train=10, val=2, test=3
playing monopoly: train=16, val=3, test=4
playing organ: train=16, val=3, test=4
playing paintball: train=32, val=7, test=7
playing piano: train=16, val=3, test=4
playing poker: train=23, val=5, test=5
playing recorder: train=29, val=6, test=7
playing saxophone: train=23, val=5, test=5
playing squash or racquetball: train=25, val=6, test=6
playing tennis: train=30, val=7, test=7
playing trombone: train=30, val=7, test=7
playing trumpet: train=26, val=6, test=6
playing ukulele: train=31, val=7, test=7
playing violin: train=30, val=7, test=7
playing volleyball: train=18, val=4, test=5
playing xylophone: train=18, val=4, test=5
pole vault: train=26, val=6, test=6
presenting weather forecast: train=30, val=6, test=7
pull ups: train=29, val=6, test=7
pumping fist: train=27, val=6, test=7
pumping gas: train=11, val=2, test=3
punching bag: train=30, val=6, test=7
punching person (boxing): train=9, val=2, test=3
push up: train=13, val=3, test=4
pushing car: train=29, val=6, test=7
pushing cart: train=32, val=7, test=8
pushing wheelchair: train=9, val=2, test=3
reading book: train=31, val=7, test=7
reading newspaper: train=7, val=2, test=2
recording music: train=7, val=2, test=2
riding a bike: train=9, val=2, test=3
riding camel: train=18, val=4, test=4
riding elephant: train=30, val=7, test=7
riding mechanical bull: train=17, val=4, test=4
riding mountain bike: train=10, val=2, test=3
riding mule: train=10, val=2, test=3
riding or walking with horse: train=31, val=7, test=7
riding scooter: train=15, val=3, test=4
riding unicycle: train=21, val=5, test=5
ripping paper: train=13, val=3, test=3
robot dancing: train=22, val=5, test=5
rock climbing: train=31, val=7, test=7
rock scissors paper: train=7, val=2, test=2
roller skating: train=25, val=5, test=6
running on treadmill: train=7, val=2, test=2
sailing: train=23, val=5, test=5
salsa dancing: train=32, val=7, test=7
sanding floor: train=13, val=3, test=3
scrambling eggs: train=19, val=4, test=5
scuba diving: train=25, val=6, test=6
setting table: train=9, val=2, test=3
shaking hands: train=15, val=3, test=4
shaking head: train=23, val=5, test=6
sharpening knives: train=8, val=2, test=2
sharpening pencil: train=17, val=4, test=4
shaving head: train=23, val=5, test=6
shaving legs: train=10, val=2, test=3
shearing sheep: train=27, val=6, test=6
shining shoes: train=13, val=3, test=4
shooting basketball: train=13, val=3, test=3
shooting goal (soccer): train=6, val=1, test=2
shot put: train=27, val=6, test=6
shoveling snow: train=23, val=5, test=5
shredding paper: train=7, val=2, test=2
shuffling cards: train=19, val=4, test=5
side kick: train=25, val=6, test=6
sign language interpreting: train=8, val=2, test=2
singing: train=32, val=7, test=7
situp: train=20, val=5, test=5
skateboarding: train=30, val=7, test=7
ski jumping: train=28, val=6, test=7
skiing (not slalom or crosscountry): train=31, val=7, test=7
skiing crosscountry: train=10, val=2, test=3
skiing slalom: train=12, val=3, test=3
skipping rope: train=10, val=2, test=3
skydiving: train=10, val=2, test=3
slacklining: train=20, val=4, test=5
slapping: train=9, val=2, test=2
sled dog racing: train=20, val=5, test=5
smoking: train=24, val=5, test=6
smoking hookah: train=19, val=4, test=5
snatch weight lifting: train=25, val=6, test=6
sneezing: train=10, val=2, test=3
sniffing: train=6, val=2, test=2
snorkeling: train=27, val=6, test=6
snowboarding: train=24, val=5, test=6
snowkiting: train=32, val=7, test=8
snowmobiling: train=14, val=3, test=4
somersaulting: train=26, val=6, test=6
spinning poi: train=31, val=7, test=7
spray painting: train=23, val=5, test=5
spraying: train=10, val=2, test=3
springboard diving: train=7, val=2, test=2
squat: train=31, val=7, test=7
sticking tongue out: train=18, val=4, test=5
stomping grapes: train=9, val=2, test=2
stretching arm: train=16, val=4, test=4
stretching leg: train=20, val=4, test=5
strumming guitar: train=9, val=2, test=2
surfing crowd: train=23, val=5, test=6
surfing water: train=19, val=4, test=5
sweeping floor: train=13, val=3, test=4
swimming backstroke: train=30, val=6, test=7
swimming breast stroke: train=22, val=5, test=5
swimming butterfly stroke: train=16, val=4, test=4
swing dancing: train=11, val=3, test=3
swinging legs: train=7, val=2, test=2
swinging on something: train=10, val=2, test=3
sword fighting: train=9, val=2, test=2
tai chi: train=29, val=6, test=7
taking a shower: train=6, val=1, test=2
tango dancing: train=32, val=7, test=7
tap dancing: train=25, val=5, test=6
tapping guitar: train=20, val=5, test=5
tapping pen: train=16, val=4, test=4
tasting beer: train=13, val=3, test=3
tasting food: train=11, val=3, test=3
testifying: train=10, val=2, test=3
texting: train=16, val=4, test=4
throwing axe: train=20, val=5, test=5
throwing ball: train=15, val=3, test=4
throwing discus: train=30, val=7, test=7
tickling: train=11, val=3, test=3
tobogganing: train=32, val=7, test=8
tossing coin: train=9, val=2, test=3
tossing salad: train=9, val=2, test=3
training dog: train=10, val=2, test=3
trapezing: train=20, val=4, test=5
trimming or shaving beard: train=25, val=5, test=6
trimming trees: train=16, val=3, test=4
triple jump: train=20, val=5, test=5
tying bow tie: train=6, val=2, test=2
tying knot (not on a tie): train=20, val=5, test=5
tying tie: train=16, val=3, test=4
unboxing: train=19, val=4, test=5
unloading truck: train=7, val=2, test=2
using computer: train=23, val=5, test=5
using remote controller (not gaming): train=12, val=3, test=3
using segway: train=7, val=2, test=2
vault: train=13, val=3, test=3
waiting in line: train=9, val=2, test=2
walking the dog: train=30, val=6, test=7
washing dishes: train=27, val=6, test=7
washing feet: train=22, val=5, test=5
washing hair: train=7, val=2, test=2
washing hands: train=23, val=5, test=6
water skiing: train=20, val=4, test=5
water sliding: train=7, val=2, test=2
watering plants: train=16, val=4, test=4
waxing back: train=11, val=3, test=3
waxing chest: train=19, val=4, test=5
waxing eyebrows: train=16, val=3, test=4
waxing legs: train=23, val=5, test=6
weaving basket: train=19, val=4, test=5
welding: train=19, val=4, test=5
whistling: train=7, val=2, test=2
windsurfing: train=31, val=7, test=7
wrapping present: train=20, val=4, test=5
wrestling: train=10, val=2, test=3
writing: train=17, val=4, test=4
yawning: train=6, val=2, test=2
yoga: train=26, val=6, test=6
zumba: train=30, val=6, test=7

DONE!
Dataset saved to: data/Kinetics_split

In [13]:
df = pd.read_csv('all_models_full_data.csv')

In [14]:
df

,Unnamed: 0.1,Unnamed: 0,Epoch,Accuracy_train,Accuracy_val,Exp_name,Overfit
0,0.0,NaN,0,0.377823,0.487479,debug_yolo_LSTM_30_naked,-0.109656
1,1.0,NaN,1,0.532426,0.564274,debug_yolo_LSTM_30_naked,-0.031848
2,2.0,NaN,2,0.602779,0.624374,debug_yolo_LSTM_30_naked,-0.021595
3,3.0,NaN,3,0.660973,0.639399,debug_yolo_LSTM_30_naked,0.021574
4,4.0,NaN,4,0.683845,0.659432,debug_yolo_LSTM_30_naked,0.024412
...,...,...,...,...,...,...,...
530,NaN,NaN,10,0.835008,0.785967,debug_yolo_transformer_15_withobject,NaN
531,NaN,NaN,11,0.847568,0.772406,debug_yolo_transformer_15_withobject,NaN
532,NaN,NaN,12,0.846865,0.750590,debug_yolo_transformer_15_withobject,NaN
533,NaN,NaN,13,0.856009,0.778302,debug_yolo_transformer_15_withobject,NaN
534,NaN,NaN,14,0.881230,0.796580,debug_yolo_transformer_15_withobject,NaN

In [15]:
df['Exp_name'].unique().item

<bound method ExtensionArray.item of <StringArray>
[                    'debug_yolo_LSTM_30_naked',
                'debug_mediapipe_LSTM_30_naked',
        'debug_yolo_LSTM_30_naked_noskipframes',
         'debug_yolo_GRU_30_naked_noskipframes',
 'debug_yolo_transformer_30_naked_noskipframes',
                    'debug_yolo_LSTM_30_smooth',
                     'debug_yolo_GRU_30_smooth',
             'debug_yolo_transformer_30_smooth',
         'debug_mediapipe_LSTM_30_noskipframes',
          'debug_mediapipe_GRU_30_noskipframes',
  'debug_mediapipe_transformer_30_noskipframes',
            'debug_mediapipe_LSTM_noskipframes',
             'debug_yolo_LSTM_15_withoutObject',
             'debug_yolo_LSTM_25_withoutObject',
              'debug_yolo_GRU_15_withoutObject',
      'debug_yolo_transformer_15_withoutObject',
                'debug_yolo_LSTM_15_withobject',
                 'debug_yolo_GRU_15_withobject',
         'debug_yolo_transformer_15_withobject']
Length: 19, dtype: str>

In [16]:
df.groupby('Exp_name').max()['Accuracy_val']

Exp_name
debug_mediapipe_GRU_30_noskipframes             0.874580
debug_mediapipe_LSTM_30_naked                   0.869369
debug_mediapipe_LSTM_30_noskipframes            0.871264
debug_mediapipe_LSTM_noskipframes               0.868981
debug_mediapipe_transformer_30_noskipframes     0.857471
debug_yolo_GRU_15_withobject                    0.800708
debug_yolo_GRU_15_withoutObject                 0.740458
debug_yolo_GRU_30_naked_noskipframes            0.880759
debug_yolo_GRU_30_smooth                        0.873646
debug_yolo_LSTM_15_withobject                   0.769458
debug_yolo_LSTM_15_withoutObject                0.772265
debug_yolo_LSTM_25_withoutObject                0.784987
debug_yolo_LSTM_30_naked                        0.864775
debug_yolo_LSTM_30_naked_noskipframes           0.887082
debug_yolo_LSTM_30_smooth                       0.868231
debug_yolo_transformer_15_withobject            0.796580
debug_yolo_transformer_15_withoutObject         0.723919
debug_yolo_transformer_30_naked_noskipframes    0.892502
debug_yolo_transformer_30_smooth                0.878159
Name: Accuracy_val, dtype: float64

In [17]:
df['Overfit'] = df['Accuracy_train'] - df['Accuracy_val']

In [18]:
df.groupby('Exp_name').max()[['Accuracy_val', 'Overfit']]

                                              Accuracy_val   Overfit
Exp_name
debug_mediapipe_GRU_30_noskipframes               0.874580  0.120258
debug_mediapipe_LSTM_30_naked                     0.869369  0.135572
debug_mediapipe_LSTM_30_noskipframes              0.871264  0.132159
debug_mediapipe_LSTM_noskipframes                 0.868981  0.132369
debug_mediapipe_transformer_30_noskipframes       0.857471  0.116538
debug_yolo_GRU_15_withobject                      0.800708  0.087255
debug_yolo_GRU_15_withoutObject                   0.740458  0.070580
debug_yolo_GRU_30_naked_noskipframes              0.880759  0.088612
debug_yolo_GRU_30_smooth                          0.873646  0.093170
debug_yolo_LSTM_15_withobject                     0.769458  0.072766
debug_yolo_LSTM_15_withoutObject                  0.772265  0.075741
debug_yolo_LSTM_25_withoutObject                  0.784987  0.152742
debug_yolo_LSTM_30_naked                          0.864775  0.132541
debug_yolo_LSTM_30_naked_noskipframes             0.887082  0.110462
debug_yolo_LSTM_30_smooth                         0.868231  0.129991
debug_yolo_transformer_15_withobject              0.796580  0.096275
debug_yolo_transformer_15_withoutObject           0.723919  0.087089
debug_yolo_transformer_30_naked_noskipframes      0.892502  0.085457
debug_yolo_transformer_30_smooth                  0.878159  0.082618

In [9]:
df.to_csv("all_models_full_data.csv")

In [ ]:
"""
debug_yolo_GRU_15_withobject	0.800708	0.087255
debug_yolo_GRU_15_withoutObject	0.740458	0.070580

debug_yolo_LSTM_15_withobject	    0.769458	0.072766
debug_yolo_LSTM_15_withoutObject	0.772265	0.075741
debug_yolo_LSTM_25_withoutObject	0.784987	0.152742

debug_yolo_transformer_15_withobject	0.796580	0.096275
debug_yolo_transformer_15_withoutObject	0.723919	0.087089

"""